loglevel = "trace" # Other values include trace, debug, warn and error

# which ptp network to participate in?
sdo-id = 0
domain = 0
priority1 = 251 # Dante hardware devices use 249 in PTPv2
virtual-system-clock = true
virtual-system-clock-base = "monotonic_raw"
usrvclock-export = true

# Add one of these per network interface in your system
[[port]]
interface = "eth0"
network-mode = "ipv4" #can also be ipv6 or ethernet

# hardware-clock = auto | required | none | index (default: auto)
hardware-clock = "auto"

protocol-version = "PTPv1"